title = "Клуб айкидо и кэндзюцу Синто"
baseURL = "http://localhost"
languageCode = "ru-RU"
theme = "ananke"


DefaultContentLanguage = "ru"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Shinto Aikido and Kenjutsu Club"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    title = "Shinto Aikido and Kenjutsu Club"
    weight = 2
    contentDir = "content/fr"
  [languages.de]
    title = "Shinto Aikido and Kenjutsu Club"
    weight = 1
    contentDir = "content/de"
  [languages.ru]
    title = "Клуб айкидо и кэндзюцу Синто"
    weight = 2
    contentDir = "content/ru"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Путь начинается с одного шага. И никогда не заканчивается."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[[params.ananke_socials]]
name = "youtube"
url = "https://youtube.com/playlist?list=PLCs0Mi4tR71vnRzAreyuah8dj0THoQZux"

